[package]
name = "test-parachain-undying-collator"
description = "Collator for the undying test parachain"
edition.workspace = true
version.workspace = true
authors.workspace = true

[[bin]]
name = "undying-collator"
path = "src/main.rs"

[[bin]]
name = "undying_collator_puppet_worker"
path = "bin/puppet_worker.rs"

[dependencies]
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
clap = { version = "4.0.9", features = ["derive"] }
futures = "0.3.19"
futures-timer = "3.0.2"
log = "0.4.17"

test-parachain-undying = { path = ".." }
vine-primitives = { path = "../../../../primitives" }
vine-cli = { path = "../../../../cli" }
vine-service = { path = "../../../../node/service", features = [] }
vine-node-primitives = { path = "../../../../node/primitives" }
vine-node-subsystem = { path = "../../../../node/subsystem" }

sc-cli = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sp-core = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sc-service = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }

# This one is tricky. Even though it is not used directly by the collator, we still need it for the
# `puppet_worker` binary, which is required for the integration test. However, this shouldn't be
# a big problem since it is used transitively anyway.
vine-node-core-pvf = { path = "../../../../node/core/pvf" }

[dev-dependencies]
vine-parachain = { path = "../../.." }
vine-test-service = { path = "../../../../node/test/service" }

substrate-test-utils = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sc-service = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sp-keyring = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }

tokio = { version = "1.22.0", features = ["macros"] }
