[package]
name = "vine-dispute-distribution"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../../gum" }
derive_more = "0.99.17"
parity-scale-codec = { version = "3.1.5", features = ["std"] }
vine-primitives = { path = "../../../primitives" }
vine-erasure-coding = { path = "../../../erasure-coding" }
vine-node-subsystem = {path = "../../subsystem" }
vine-node-network-protocol = { path = "../../network/protocol" }
vine-node-subsystem-util = { path = "../../subsystem-util" }
vine-node-primitives = { path = "../../primitives" }
sc-network = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sp-application-crypto = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sp-keystore = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
thiserror = "1.0.31"
fatality = "0.0.6"
lru = "0.8.0"
indexmap = "1.9.1"

[dev-dependencies]
async-trait = "0.1.57"
vine-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sp-tracing = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sc-keystore = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
futures-timer = "3.0.2"
assert_matches = "1.4.0"
lazy_static = "1.4.0"
vine-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
