[package]
name = "vine-collator-protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
always-assert = "0.1.2"
bitvec = { version = "1.0.1", default-features = false, features = ["alloc"] }
futures = "0.3.21"
futures-timer = "3"
gum = { package = "tracing-gum", path = "../../gum" }

sp-core = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sp-runtime = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sp-keystore = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }

vine-primitives = { path = "../../../primitives" }
vine-node-network-protocol = { path = "../../network/protocol" }
vine-node-primitives = { path = "../../primitives" }
vine-node-subsystem-util = { path = "../../subsystem-util" }
vine-node-subsystem = {path = "../../subsystem" }
fatality = "0.0.6"
thiserror = "1.0.31"

[dev-dependencies]
log = "0.4.17"
env_logger = "0.9.0"
assert_matches = "1.4.0"

sp-core = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", features = ["std"] , branch = "mainnet-peer" }
sp-keyring = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sc-network = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
parity-scale-codec = { version = "3.1.5", features = ["std"] }

vine-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
vine-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
