[package]
name = "test-parachain-adder-collator"
description = "Collator for the adder test parachain"
version.workspace = true
authors.workspace = true
edition.workspace = true

[[bin]]
name = "adder-collator"
path = "src/main.rs"

[[bin]]
name = "adder_collator_puppet_worker"
path = "bin/puppet_worker.rs"

[dependencies]
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
clap = { version = "4.0.9", features = ["derive"] }
futures = "0.3.21"
futures-timer = "3.0.2"
log = "0.4.17"

test-parachain-adder = { path = ".." }
peer-primitives = { path = "../../../../primitives" }
vine-cli = { path = "../../../../cli" }
peer-service = { path = "../../../../node/service", features = [] }
peer-node-primitives = { path = "../../../../node/primitives" }
peer-node-subsystem = { path = "../../../../node/subsystem" }

sc-cli = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sp-core = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sc-service = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }

# This one is tricky. Even though it is not used directly by the collator, we still need it for the
# `puppet_worker` binary, which is required for the integration test. However, this shouldn't be
# a big problem since it is used transitively anyway.
peer-node-core-pvf = { path = "../../../../node/core/pvf" }

[dev-dependencies]
peer-parachain = { path = "../../.." }
peer-test-service = { path = "../../../../node/test/service" }

substrate-test-utils = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sc-service = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sp-keyring = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }

tokio = { version = "1.22.0", features = ["macros"] }
