version: '3'
services:
  vine:
    ports:
      - "127.0.0.1:30333:30333/tcp"
      - "127.0.0.1:9933:9933/tcp"
    image: parity/vine:latest
    volumes:
      - "vine-data:/data"
    command: |
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-cors all
      --prometheus-external

    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
      - "9615:9615"

volumes:
  vine-data:
