[package]
name = "vine-node-core-dispute-coordinator"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum" }
parity-scale-codec = "3.1.5"
kvdb = "0.13.0"
thiserror = "1.0.31"
lru = "0.8.0"
fatality = "0.0.6"

vine-primitives = { path = "../../../primitives" }
vine-node-primitives = { path = "../../primitives" }
vine-node-subsystem = { path = "../../subsystem" }
vine-node-subsystem-util = { path = "../../subsystem-util" }

sc-keystore = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }


[dev-dependencies]
kvdb-memorydb = "0.13.0"
vine-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sp-core = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sp-keystore = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
assert_matches = "1.4.0"
test-helpers = { package = "vine-primitives-test-helpers", path = "../../../primitives/test-helpers" }
futures-timer = "3.0.2"
sp-application-crypto = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }

[features]
# If not enabled, the dispute coordinator will do nothing.
disputes = []
