[package]
name = "vine-node-core-provisioner"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum" }
thiserror = "1.0.31"
vine-primitives = { path = "../../../primitives" }
vine-node-primitives = { path = "../../primitives" }
vine-node-subsystem = { path = "../../subsystem" }
vine-node-subsystem-util = { path = "../../subsystem-util" }
rand = "0.8.5"
futures-timer = "3.0.2"
fatality = "0.0.6"

[dev-dependencies]
sp-application-crypto = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
sp-keystore = { git = "ssh://git@github.com/PEER-Inc/peer-substrate.git", branch = "mainnet-peer" }
vine-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
test-helpers = { package = "vine-primitives-test-helpers", path = "../../../primitives/test-helpers" }
